language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.1
before_script: bundle update
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: chiayo.lin@gmail.com
    on_failure: chiayo.lin@gmail.com
