branches:
  only: source

language: python

python: "2.7"

env:
  global:
    secure: 123123...123123

install:
  - pip install -r requirements.txt

script:
  - make html

after_success:
  - bash deploy.sh
