# Site settings
title: Chiayo Lin
email: chiayo.lin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer. Student. Liberal. Taiwanese.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chiayolin.org" # the base hostname & protocol for your site
twitter_username: chiayolin
github_username:  chiayolin

# Build settings
markdown: kramdown

# Gems
gems:
  - jemoji
  - jekyll-mentions
jekyll-mentions: https://github.com
