# Site settings
title: Chiayo Lin
email: chiayo.lin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer. Student. Liberal. Taiwanese.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.chiayolin.org" # the base hostname & protocol for your site
github_username:  chiayolin
twitter_username: chiayolin

# Build settings
markdown: kramdown
